services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80" # map internal port 80 to external port 80
      - "1234:1234" # map internal port 80 to external port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # use custom nginx config
    hostname: proxy
    networks:
      - to_host_network

networks:
  to_host_network:
    driver: bridge